refactor(*): optimizations and add prettier
TheAlan404/string-commands pull request #1
Opened 2022-10-22 03:47 UTC by null8626

hi

2022-10-22 10:27 UTC, TheAlan404 commented
other than that one small issue, this is a pretty good PR!

2022-10-22 14:49 UTC, null8626 commented
thanks

2022-10-26 13:00 UTC, TheAlan404 requested changes
a

2022-10-26 13:00 UTC, deniz-blue commented on src/ArgumentParser.js
> +		let braceClose = braceOpen;
this change would make outputs become something like `!add <a< <b<` instead of desired `!add <a> <b>`

2022-10-26 13:02 UTC, null8626 commented on src/ArgumentParser.js
> +		let braceClose = braceOpen;
fixed

2022-10-26 13:04 UTC, TheAlan404 requested changes
😐 `[`

2022-10-26 13:08 UTC, null8626 commented
fixed again

2022-10-26 13:09 UTC, TheAlan404 approved these changes

2022-10-26 13:09 UTC, merged